"""empty message

Revision ID: 4cdc2aab6fb7
Revises: 9d26d1daef35
Create Date: 2026-07-19 00:08:46.108067

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4cdc2aab6fb7'
down_revision: Union[str, Sequence[str], None] = '9d26d1daef35'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('has_free_consultation', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'has_free_consultation')
    # ### end Alembic commands ###
