"""empty message

Revision ID: c9de0a6e93e4
Revises: 7e7f3e698e46
Create Date: 2026-07-19 19:09:46.747387

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c9de0a6e93e4'
down_revision: Union[str, Sequence[str], None] = '7e7f3e698e46'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('consultations', sa.Column('is_viewed', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('consultations', 'is_viewed')
    # ### end Alembic commands ###
